---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.16"
  amd64: "ghcr.io/home-assistant/amd64-base:3.16"
  armhf: "ghcr.io/home-assistant/armhf-base:3.16"
  armv7: "ghcr.io/home-assistant/armv7-base:3.16"
  i386: "ghcr.io/home-assistant/i386-base:3.16"
codenotary:
  base_image: notary@home-assistant.io
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ecowitt2mqtt"
  org.opencontainers.image.description: >-
    A small CLI/web server that allows [Ecowitt](http://www.ecowitt.com) device
    data to be sent to an MQTT broker.
  org.opencontainers.image.source: "https://github.com/bachya/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
