---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
description: >-
  A small web server to send data from Ecowitt devices to an MQTT Broker
image: "ghcr.io/bachya/home-assistant-addon-ecowitt2mqtt-{arch}"
init: false
name: ecowitt2mqtt
options:
  default_battery_strategy: numeric
  diagnostics: false
  disable_calculated_data: false
  endpoint: /data/report
  hass_discovery_prefix: homeassistant
  input_unit_system: imperial
  mqtt_retain: true
  output_unit_system: imperial
  verbose: false
ports:
  "8080/tcp": 8080
ports_description:
  "8080/tcp": >-
    The port the Ecowitt gateway will use to submit data to Home Assistant
schema:
  default_battery_strategy: "list(boolean|numeric|percentage)"
  diagnostics: "bool"
  disable_calculated_data: "bool"
  endpoint: "str?"
  hass_discovery_prefix: "str?"
  hass_entity_id_prefix: "str?"
  input_unit_system: "list(imperial|metric)"
  mqtt_host: "str?"
  mqtt_password: "password?"
  mqtt_port: "port?"
  mqtt_retain: "bool"
  mqtt_username: "str?"
  output_unit_system: "list(imperial|metric)"
  verbose: "bool"
services:
  - "mqtt:want"
slug: ecowitt2mqtt
url: "https://github.com/bachya/home-assistant-addons/tree/main/ecowitt2mqtt"
version: "2022.08.2"
