---
name: Test Builds

"on":
  pull_request:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      amd64:
        type: boolean
        description: amd64
        required: false
        default: true
      aarch64:
        type: boolean
        description: aarch64
        required: false
        default: true
      armhf:
        type: boolean
        description: armhf
        required: false
        default: true
      armv7:
        type: boolean
        description: armv7
        required: false
        default: true

jobs:
  build:
    name: Test build

    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🤔 Determine which images to build
        id: build-args
        shell: bash
        run: |-
          args=()

          if [[ ${{ github.event_name }} == "pull_request" ]]; then
            args+=("--all")  # Include all checkboxes by default
          else
            local aarch64="${{ github.event.inputs.aarch64 }}"
            if [[ ! -z "$aarch64" == "true" ]]; then
              args+=("--aarch64")
            fi

            local amd64="${{ github.event.inputs.amd64 }}"
            if [[ ! -z "$amd64" == "true" ]]; then
              args+=("--amd64")
            fi

            local armhf="${{ github.event.inputs.armhf }}"
            if [[ ! -z "$armhf" == "true" ]]; then
              args+=("--armhf")
            fi

            local armv7="${{ github.event.inputs.armv7 }}"
            if [[ ! -z "$armv7" == "true" ]]; then
              args+=("--armv7")
            fi
          fi

          echo "{args}={args[@]}" >> $GITHUB_OUTPUT

      - name: 🚧 Test builds
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --target ecowitt2mqtt \
            ${{ steps.build-args.outputs.args }}
